Update compatibility for PyTorch 1.10
Summary:
When calling `import crypten`, we were getting in `crypten.serial`:

```
  from torch._utils_internal import get_source_lines_and_file
ImportError: cannot import name 'get_source_lines_and_file' from 'torch._utils_internal' (/Users/brianknott/anaconda3/envs/cryptenv/lib/python3.7/site-packages/torch/_utils_internal.py)
```

This happened because the function `get_source_lines_and_file` was removed from `torch._utils_internal`. To fix this, I copied this function from a historical version of PyTorch into `crypten.serial`.

Reviewed By: lvdmaaten

Differential Revision: D30728745

fbshipit-source-id: 01c5b209075bbb86290c8a6807dec17e072f3100