Fix load and tutorial 7 (#191)
Summary:
## Types of changes

Also, it seems there is an issue if you try to use ```torch.load``` and pass in ```kwargs```.
Received:
```
TypeError: 'src' is an invalid keyword argument for Unpickler()
```

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs change / refactoring / dependency upgrade

## Motivation and Context / Related issue
Fixes https://github.com/facebookresearch/CrypTen/issues/190

## How Has This Been Tested (if it applies)

- Run the tutorial

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

Pull Request resolved: https://github.com/facebookresearch/CrypTen/pull/191

Reviewed By: lvdmaaten

Differential Revision: D24960062

Pulled By: knottb

fbshipit-source-id: aeb366d2e7b5319c1b5b3648b5b15b84dafac79a